executors:
  java1_8:
    docker:
      - image: 'cimg/openjdk:8.0'
orbs:
  gradle: circleci/gradle@2.2.0
parameters:
  reports_path: false
version: 2.1
workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          reports_path:
          executor: java1_8
